rac_rac_user:
    resource: "@RacRacBundle/Resources/config/route/admin.yml"
    
rac_rac_gnj:
    resource: "@RacRacBundle/Resources/config/route/gnj.yml"
    
rac_rac_gca:
    resource: "@RacRacBundle/Resources/config/route/gca.yml"
