<?php

namespace Rac\RacBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GnjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GnjRepository extends EntityRepository
{
}
