rac_rac_homepage:
    path:     /index
    defaults: { _controller: RacRacBundle:Admin:home }

rac_rac_add:
    path:     /add
    defaults: { _controller: RacRacBundle:Admin:add }
    
rac_rac_create:
    path:     /create
    defaults: { _controller: RacRacBundle:Admin:create }
    methods: POST
    
rac_rac_view:
    path:     /view/{id}
    defaults: { _controller: RacRacBundle:Admin:view }
    
rac_rac_edit:
    path:     /edit/{id}
    defaults: { _controller: RacRacBundle:Admin:edit }
    
rac_rac_update:
    path:     /update/{id}
    defaults: { _controller: RacRacBundle:Admin:update }
    methods: [POST, PUT]
