rac_Gnj_homepage:
    path:     /gnj
    defaults: { _controller: RacRacBundle:Gnj:gnjhome }

rac_Gnj_add:
    path:     /gnjadd
    defaults: { _controller: RacRacBundle:Gnj:gnjadd }
    
rac_Gnj_create:
    path:     /gnjcreate
    defaults: { _controller: RacRacBundle:Gnj:gnjcreate }
    methods: POST
    
rac_Gnj_view:
    path:     /gnjview/{id}
    defaults: { _controller: RacRacBundle:Gnj:gnjview }

rac_Gnj_edit:
    path:     /gnjedit/{id}
    defaults: { _controller: RacRacBundle:Gnj:gnjedit }
    
rac_Gnj_update:
    path:     /gnjupdate/{id}
    defaults: { _controller: RacRacBundle:Gnj:gnjupdate }
    methods: [POST, PUT]